{% set version = "0.0.3" %}

package:
  name: pynco
  version: {{ version }}

source:
  fn: pynco-{{ version }}.tar.gz
  url: https://github.com/nco/pynco/archive/{{ version }}.tar.gz
  sha256: 17b85ee9675c1144e328516adbecd1383f37a69a87bb65eb4f616eee95253ccf

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - python-dateutil
    - h5py
    - netcdf4
    - numpy
    - scipy
    - nco

test:
  imports:
    - nco

about:
  home: https://github.com/nco/pynco
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: 'Python bindings to NCO.'

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
